# Generated by Django 5.2.1 on 2025-05-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenresTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActorsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='DirectorsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='MoviesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('age_rating', models.CharField(max_length=10)),
                ('runtime', models.IntegerField()),
                ('combined_rating', models.FloatField(default=0)),
                ('poster', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('movie_name', 'release_year', 'runtime')},
            },
        ),
        migrations.CreateModel(
            name='CommentsTable',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment_id', models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.commentstable')),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.moviestable')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.userstable')),
            ],
        ),
        migrations.CreateModel(
            name='WritersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='MovieGenresTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='api.genrestable')),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='api.moviestable')),
            ],
            options={
                'db_table': 'Movie_Genres',
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='MovieDirectorsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(db_column='director_id', on_delete=django.db.models.deletion.CASCADE, to='api.directorstable')),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='api.moviestable')),
            ],
            options={
                'db_table': 'Movie_Directors',
                'unique_together': {('movie', 'director')},
            },
        ),
        migrations.CreateModel(
            name='MovieActorsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, to='api.actorstable')),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='api.moviestable')),
            ],
            options={
                'db_table': 'Movie_Actors',
                'unique_together': {('movie', 'actor')},
            },
        ),
        migrations.CreateModel(
            name='RatingsTable',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_value', models.FloatField()),
                ('review_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.moviestable')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.userstable')),
            ],
            options={
                'unique_together': {('movie_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='MovieWritersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='api.moviestable')),
                ('writer', models.ForeignKey(db_column='writer_id', on_delete=django.db.models.deletion.CASCADE, to='api.writerstable')),
            ],
            options={
                'db_table': 'Movie_Writers',
                'unique_together': {('movie', 'writer')},
            },
        ),
    ]
