# Generated by Django 5.2.1 on 2025-05-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorsTable',
            new_name='Actors',
        ),
        migrations.RenameModel(
            old_name='CommentsTable',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='DirectorsTable',
            new_name='Directors',
        ),
        migrations.RenameModel(
            old_name='GenresTable',
            new_name='Genres',
        ),
        migrations.RenameModel(
            old_name='MovieActorsTable',
            new_name='MovieActors',
        ),
        migrations.RenameModel(
            old_name='MovieDirectorsTable',
            new_name='MovieDirectors',
        ),
        migrations.RenameModel(
            old_name='MovieGenresTable',
            new_name='MovieGenres',
        ),
        migrations.RenameModel(
            old_name='MoviesTable',
            new_name='Movies',
        ),
        migrations.RenameModel(
            old_name='MovieWritersTable',
            new_name='MovieWriters',
        ),
        migrations.RenameModel(
            old_name='RatingsTable',
            new_name='Ratings',
        ),
        migrations.RenameModel(
            old_name='UsersTable',
            new_name='Users',
        ),
        migrations.RenameModel(
            old_name='WritersTable',
            new_name='Writers',
        ),
    ]
