# Generated by Django 5.2.1 on 2025-05-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_actorstable_actors_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='ratings',
            table='Ratings',
        ),
    ]
