# Generated by Django 5.2.1 on 2025-05-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comments_table_alter_ratings_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='directors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='movieactors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moviedirectors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moviegenres',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moviewriters',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='writers',
            options={'managed': False},
        ),
    ]
