# Generated by Django 5.2.1 on 2025-05-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_actors_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actors',
            table='Actors',
        ),
        migrations.AlterModelTable(
            name='directors',
            table='Directors',
        ),
        migrations.AlterModelTable(
            name='genres',
            table='Genres',
        ),
        migrations.AlterModelTable(
            name='movies',
            table='Movies',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='writers',
            table='Writers',
        ),
    ]
